from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import HorizontalBarChart

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#003366")
title_style.spaceAfter = 20

subtitle_style = styles["Heading2"]
subtitle_style.textColor = HexColor("#004488")
subtitle_style.spaceAfter = 12

heading_style = styles["Heading3"]
heading_style.textColor = HexColor("#005A9C")
heading_style.spaceAfter = 8

normal_style = styles["BodyText"]
normal_style.leading = 18
normal_style.spaceAfter = 8

small_style = styles["BodyText"]
small_style.fontSize = 9
small_style.textColor = colors.grey

center_style = styles["BodyText"]
center_style.alignment = TA_CENTER

def header(canvas, doc):

    canvas.saveState()

    canvas.setFillColor(HexColor("#003366"))
    canvas.rect(0, 770, 700, 40, fill=1)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 18)
    canvas.drawString(40, 783, "🛡 AccessGuard AI")

    canvas.setFont("Helvetica",10)
    canvas.drawRightString(
        560,
        783,
        "Enterprise IAM Security Audit"
    )

    canvas.restoreState()

def footer(canvas, doc):

    canvas.saveState()

    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(40,35,560,35)

    canvas.setFont("Helvetica",9)
    canvas.setFillColor(colors.grey)

    canvas.drawString(
        40,
        20,
        "Generated by AccessGuard AI"
    )

    canvas.drawRightString(
        560,
        20,
        f"Page {doc.page}"
    )

    canvas.restoreState()

def build_cover(story):

    story.append(Spacer(1,1.2*inch))

    story.append(
        Paragraph(
            "🛡 ACCESSGUARD AI",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Enterprise Identity Security Audit Report",
            subtitle_style
        )
    )

    story.append(Spacer(1,0.4*inch))

    story.append(
        Paragraph(
            "<b>CONFIDENTIAL</b>",
            center_style
        )
    )

    story.append(Spacer(1,0.8*inch))

    story.append(
        Paragraph(
            f"Generated : {datetime.now().strftime('%d %B %Y %H:%M')}",
            center_style
        )
    )

    story.append(
        Paragraph(
            "Generated using AccessGuard AI Threat Intelligence Engine",
            center_style
        )
    )

    story.append(PageBreak())

def risk_colour(score):

    if score >= 80:
        return colors.red

    if score >= 60:
        return colors.orange

    if score >= 30:
        return colors.gold

    return colors.green

def risk_chart(score):

    drawing = Drawing(350,45)

    chart = HorizontalBarChart()

    chart.x = 0
    chart.y = 5
    chart.height = 20
    chart.width = 250

    chart.data = [[score]]

    chart.valueAxis.valueMin = 0
    chart.valueAxis.valueMax = 100

    chart.categoryAxis.visible = False

    chart.bars[0].fillColor = risk_colour(score)

    drawing.add(chart)

    return drawing

# --------------------------------------------------------
# USER PROFILE DASHBOARD
# --------------------------------------------------------

def build_dashboard(story, user_data):

    story.append(Paragraph("Executive Security Dashboard", subtitle_style))
    story.append(Spacer(1, 0.2 * inch))

    score = int(user_data["risk_score"])

    if score >= 80:
        badge = "🔴 CRITICAL"
        badge_color = colors.red
    elif score >= 60:
        badge = "🟠 HIGH"
        badge_color = colors.orange
    elif score >= 30:
        badge = "🟡 MEDIUM"
        badge_color = colors.gold
    else:
        badge = "🟢 LOW"
        badge_color = colors.green

    data = [
        ["Username", str(user_data["username"])],
        ["User ID", str(user_data["user_id"])],
        ["Risk Score", f"{score}/100"],
        ["Risk Tier", badge],
        ["Failed Logins", str(user_data["failed_logins"])],
        ["Days Inactive", str(user_data["days_inactive"])],
        [
            "Privileged User",
            "YES" if user_data["is_privileged_user"] else "NO",
        ],
    ]

    table = Table(data, colWidths=[2.4 * inch, 3.4 * inch])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), HexColor("#003366")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),

                ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

                ("TOPPADDING", (0, 0), (-1, -1), 10),

                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 0.35 * inch))

    story.append(
        Paragraph(
            "<b>Overall Risk Score</b>",
            heading_style,
        )
    )

    story.append(risk_chart(score))

    story.append(
        Paragraph(
            f"<font color='{badge_color.hexval()}'><b>{badge}</b></font>",
            normal_style,
        )
    )

    story.append(Spacer(1, 0.4 * inch))


# --------------------------------------------------------
# COMPLIANCE TABLE
# --------------------------------------------------------

def build_compliance_table(story, user_data):

    story.append(
        Paragraph(
            "Regulatory Compliance Assessment",
            subtitle_style,
        )
    )

    impact = str(user_data["regulatory_impact"])

    def status(keyword):
        if keyword in impact:
            return "❌ Failed"
        return "✅ Compliant"

    table_data = [

        [
            "Framework",
            "Status",
        ],

        [
            "ISO 27001",
            status("ISO"),
        ],

        [
            "SOC 2",
            status("SOC"),
        ],

        [
            "GDPR",
            status("GDPR"),
        ],

    ]

    compliance_table = Table(
        table_data,
        colWidths=[3 * inch, 2.5 * inch],
    )

    compliance_table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#003366")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

                ("TOPPADDING", (0, 0), (-1, -1), 10),

            ]
        )
    )

    story.append(compliance_table)

    story.append(Spacer(1, 0.45 * inch))


# --------------------------------------------------------
# QUICK METRICS
# --------------------------------------------------------

def build_metrics(story, user_data):

    story.append(
        Paragraph(
            "Identity Risk Metrics",
            subtitle_style,
        )
    )

    metrics = [

        [
            "Metric",
            "Value",
        ],

        [
            "Authentication Failures",
            str(user_data["failed_logins"]),
        ],

        [
            "Dormant Days",
            str(user_data["days_inactive"]),
        ],

        [
            "Risk Score",
            f"{user_data['risk_score']}/100",
        ],

        [
            "Privileged Account",
            "YES"
            if user_data["is_privileged_user"]
            else "NO",
        ],

    ]

    metric_table = Table(metrics)

    metric_table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#005A9C")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("TOPPADDING", (0, 0), (-1, -1), 8),

            ]
        )
    )

    story.append(metric_table)

    story.append(PageBreak())

# --------------------------------------------------------
# USER PROFILE DASHBOARD
# --------------------------------------------------------

def build_dashboard(story, user_data):

    story.append(Paragraph("Executive Security Dashboard", subtitle_style))
    story.append(Spacer(1, 0.2 * inch))

    score = int(user_data["risk_score"])

    if score >= 80:
        badge = "🔴 CRITICAL"
        badge_color = colors.red
    elif score >= 60:
        badge = "🟠 HIGH"
        badge_color = colors.orange
    elif score >= 30:
        badge = "🟡 MEDIUM"
        badge_color = colors.gold
    else:
        badge = "🟢 LOW"
        badge_color = colors.green

    data = [
        ["Username", str(user_data["username"])],
        ["User ID", str(user_data["user_id"])],
        ["Risk Score", f"{score}/100"],
        ["Risk Tier", badge],
        ["Failed Logins", str(user_data["failed_logins"])],
        ["Days Inactive", str(user_data["days_inactive"])],
        [
            "Privileged User",
            "YES" if user_data["is_privileged_user"] else "NO",
        ],
    ]

    table = Table(data, colWidths=[2.4 * inch, 3.4 * inch])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), HexColor("#003366")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),

                ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

                ("TOPPADDING", (0, 0), (-1, -1), 10),

                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 0.35 * inch))

    story.append(
        Paragraph(
            "<b>Overall Risk Score</b>",
            heading_style,
        )
    )

    story.append(risk_chart(score))

    story.append(
        Paragraph(
            f"<font color='{badge_color.hexval()}'><b>{badge}</b></font>",
            normal_style,
        )
    )

    story.append(Spacer(1, 0.4 * inch))


# --------------------------------------------------------
# COMPLIANCE TABLE
# --------------------------------------------------------

def build_compliance_table(story, user_data):

    story.append(
        Paragraph(
            "Regulatory Compliance Assessment",
            subtitle_style,
        )
    )

    impact = str(user_data["regulatory_impact"])

    def status(keyword):
        if keyword in impact:
            return "❌ Failed"
        return "✅ Compliant"

    table_data = [

        [
            "Framework",
            "Status",
        ],

        [
            "ISO 27001",
            status("ISO"),
        ],

        [
            "SOC 2",
            status("SOC"),
        ],

        [
            "GDPR",
            status("GDPR"),
        ],

    ]

    compliance_table = Table(
        table_data,
        colWidths=[3 * inch, 2.5 * inch],
    )

    compliance_table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#003366")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

                ("TOPPADDING", (0, 0), (-1, -1), 10),

            ]
        )
    )

    story.append(compliance_table)

    story.append(Spacer(1, 0.45 * inch))


# --------------------------------------------------------
# QUICK METRICS
# --------------------------------------------------------

def build_metrics(story, user_data):

    story.append(
        Paragraph(
            "Identity Risk Metrics",
            subtitle_style,
        )
    )

    metrics = [

        [
            "Metric",
            "Value",
        ],

        [
            "Authentication Failures",
            str(user_data["failed_logins"]),
        ],

        [
            "Dormant Days",
            str(user_data["days_inactive"]),
        ],

        [
            "Risk Score",
            f"{user_data['risk_score']}/100",
        ],

        [
            "Privileged Account",
            "YES"
            if user_data["is_privileged_user"]
            else "NO",
        ],

    ]

    metric_table = Table(metrics)

    metric_table.setStyle(
        TableStyle(
            [

                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#005A9C")),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("TOPPADDING", (0, 0), (-1, -1), 8),

            ]
        )
    )

    story.append(metric_table)

    story.append(PageBreak())

# --------------------------------------------------------
# RECOMMENDATIONS
# --------------------------------------------------------

def build_recommendations(story,user_data):

    story.append(
        Paragraph(
            "Executive Recommendations",
            subtitle_style
        )
    )

    recommendations=[]

    if user_data["failed_logins"]>=5:

        recommendations.append(
            "Enable Multi-Factor Authentication immediately."
        )

    if user_data["days_inactive"]>90:

        recommendations.append(
            "Disable or archive dormant accounts."
        )

    if user_data["is_privileged_user"]:

        recommendations.append(
            "Review privileged role assignments."
        )

    if user_data["risk_score"]>=80:

        recommendations.append(
            "Perform an immediate security investigation."
        )

    recommendations.extend([
        "Rotate passwords and API credentials.",
        "Review access logs.",
        "Implement Zero Trust access policies.",
        "Conduct quarterly IAM audits."
    ])

    for rec in recommendations:

        story.append(
            Paragraph(
                f"• {rec}",
                normal_style
            )
        )

    story.append(PageBreak())

# --------------------------------------------------------
# FINAL SUMMARY
# --------------------------------------------------------

def build_summary(story,user_data):

    story.append(
        Paragraph(
            "Executive Conclusion",
            subtitle_style
        )
    )

    score=user_data["risk_score"]

    if score>=80:

        colour="red"
        verdict="CRITICAL"

    elif score>=60:

        colour="orange"
        verdict="HIGH"

    elif score>=30:

        colour="gold"
        verdict="MEDIUM"

    else:

        colour="green"
        verdict="LOW"

    story.append(

        Paragraph(

        f"""
        <font color="{colour}">
        <b>Overall Security Rating : {verdict}</b>
        </font>
        """,

        heading_style

        )

    )

    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(

        Paragraph(

        """
        AccessGuard AI recommends continuous
        monitoring of user identities,
        implementation of Zero Trust principles,
        privileged access reviews,
        and regular compliance audits
        to reduce organizational risk.
        """,

        normal_style

        )

    )

    story.append(
        Spacer(1,0.4*inch)
    )

    story.append(

        Paragraph(

        "<b>Generated by AccessGuard AI Enterprise Security Platform</b>",

        center_style

        )

    )

    story.append(

        Paragraph(

        datetime.now().strftime("%d %B %Y %H:%M"),

        center_style

        )

    )

def generate_pdf(user_data, ai_text):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=60,
        bottomMargin=50,
    )

    story = []

    build_cover(story)

    build_dashboard(story, user_data)

    build_compliance_table(story, user_data)

    build_metrics(story, user_data)

    build_ai_report(story, ai_text)

    build_recommendations(story, user_data)

    build_summary(story, user_data)

    doc.build(
        story,
        onFirstPage=header,
        onLaterPages=header,
    )

    buffer.seek(0)

    return buffer.getvalue()